### ISSUE TITLE
Kernel v6.6.4 aufs boot error

### ISSUE THREAD

**Issue by roadie2** [sirlucjan/kernel-patches#16]
Using 0001-aufs-6.6-merge-v20231106.patch, kernel patch applies without errors and kernel compiles without errors. Booting gives this error: "mkdir: can't create directory '/union/' : Operation not permitted"

The kernel is being used with Porteus Linux and the boot halts immediately. I've also seen reports from Puppy Linux users regarding a kernel panic with kernel-v6.6.4 and aufs, although overlay boots well. 

I've compared the diff files between kernel-v6.6.3 and 6.6.4, but I don't see what could be causing the issue, bearing in mind that I don't have great knowledge concerning the kernel. Kernel-v6.6.3 boots well with the same patch.

**Comment by sirlucjan** [comment]
Bug was reported: https://github.com/sfjro/aufs-standalone/issues/32

**Comment by roadie2** [comment]
A fix has been found, a new patch is expected in due time.
