### ISSUE TITLE
6.7 amd-pstate-patches-v4+ broken on AM4

### ISSUE THREAD

**Issue by DiabeticCrab** [sirlucjan/kernel-patches#18]
The first line is printed for each logical processor core (0-23 in my case). Here's the correspondig dmesg snippet:

```
[    0.675906] processor cpu0: min_freq(550000) or max_freq(0) or nominal_freq(0)                         value is incorrect
(...)
[    0.790953] amd_pstate: failed to register with return -19
```

The CPUfreq will then lock the CPU at 550Mhz until amd_pstate is manually unloaded with the sysfs interface, such that acpi-cpufreq can take over. Following that, amd_pstate cannot be set to "active" or "guided" again.

Seems like some change was introduced that makes the driver crap itself when it gets a zero value for max_freq or nominal_freq. It should get them from ACPI-CPPC, but doesn't. The min_freq is correct though.

With v3 and prior, aswell as on earlier kernel versions, I can use the EPP and non-EPP versions of the driver just fine without any issues or missing functionality.

System: 5900X AGESA 1.2.0.B
X570 Aorus Pro r1.0
Kernel 6.7.2 & 6.7.3
cmdline: amd_pstate=active amd_prefcore=enable
Affected patches: amd-pstate-patches v4-v6
Bios: CPPC explicitly enabled

It's up to upstream to fix this, but I thought you and the CachyOS folks would like to know.

**Comment by sirlucjan** [comment]
Thanks for the notification. We have withdrawn these patches from CachyOS.

**Comment by sirlucjan** [comment]
Probably these patches work only with kernel 6.8, I removed them from the 6.7 branch
