### ISSUE TITLE
[not an issue] Collaboration?

### ISSUE THREAD

**Issue by torvic9** [sirlucjan/kernel-patches#2]
Hi,
first of all thanks for your great work!
Would you be interested in some sort of "collaboration"?
I notice that in some ways we're independently doing the same work when it comes to assembling/regrouping patches, albeit in a different way (I don't separate patches from the actual kernel builds PKGBUILD). My current kernel is [here](https://github.com/torvic9/linux59-klitoris).
Let me know what you think of it.

**Comment by sirlucjan** [comment]
I would love to. The two of you can always get a better effect than alone. I am very interested in cooperation.

**Comment by torvic9** [comment]
Sorry for not replying earlier...
I think the goal should be to avoid doing the same thing. For example we both have the zstd 1.4.6 patch, I think it's enough if just one of us does it.
Not sure about details yet, I'm not so good at organising things^^
Maybe in a first step we could notify each other about interesting patches.

**Comment by sirlucjan** [comment]
I think there is nothing wrong with finding the same patches here. I use them to make my patchset (https://github.com/sirlucjan/linux-lucjan) and it is convenient to keep it at home. The fact that we use the same patches simply means that they are good :D 

I think a pretty good solution would be to create a common repository and throw some patches, solutions - we aim at a similar target (Arch and derivatives) so it wouldn't be problematic.

**Comment by torvic9** [comment]
Yes, that sounds like a good idea. You know more about this stuff than me anyway :)
I'm not a coder and I'm mostly just cherry-picking other people's work...
A common repo could also help to detect problems or fix patches that don't apply cleanly on newer kernels.

**Comment by sirlucjan** [comment]
I am not a professional programmer either. I think that such a repository will be quite a good thing. You will just have to think about how it should work. Soon I will let you know a little bit more about it, I will try to find the best solution. You know - the more people working on a given repository, the less chance that a mistake will creep in.

**Comment by torvic9** [comment]
Yes exactly, that's the point. Thank you for having a look at it. No hurry, I will not have much time the next 2 weeks due to "real life" :)

**Comment by sirlucjan** [comment]
Great. So we will come back to this topic. Thanks for the offer and see you soon!
