### ISSUE TITLE
0001-aufs-6.11-merge-v20240923.patch does not patch against 6.11.2

### ISSUE THREAD

**Issue by texstar** [sirlucjan/kernel-patches#21]
0001-aufs-6.11-merge-v20240923.patch does not patch against Kernel 6.11.2. Please fix when time allows. Thank you so much.

**Comment by texstar** [comment]
It patches clean but the kernel fails to build.  It appears quite a few errors in the build process.

**Comment by sirlucjan** [comment]
So you've to ask developer to fix it.

**Comment by texstar** [comment]
Ok, no problem.
