### ISSUE TITLE
Create Single patch like xanmod please

### ISSUE THREAD

**Issue by RuiKenichi** [sirlucjan/kernel-patches#6]
[like this patch](https://github.com/xanmod/linux/releases/download/5.15.14-xanmod1-tt/patch-5.15.14-xanmod1-tt.xz)

**Comment by sirlucjan** [comment]
Such a patch has been around for several years. It contains, for example:

- PRJC
- CaCULE
- UKSM
- AUFS
- patches for BFQ
- MGLRU
- LRNG
- patches for ZSTD
- patches for BTRFS
- patches from ClearLinux

Sources: https://github.com/sirlucjan/linux-lucjan
