### ISSUE TITLE
Build breakage with 0005-tty-Allow-setting-the-number-of-available-virtual-TT.patch 

### ISSUE THREAD

**Issue by ms178** [sirlucjan/kernel-patches#9]
Hello Piotr, while trying out other patches of your repo (with Vanilla sources this time), I came across an issue with the mentioned patch within the fixes-miscellaneous folder.

`0005-tty-Allow-setting-the-number-of-available-virtual-TT.patch` causes a compilation failure when using the `make binrpm-pkg` or `make rpm-pkg` script with the following error:

`HDRINST usr/include/linux/version.h
error: include/uapi/linux/vt.h: leak CONFIG_NR_TTY_DEVICES to user-space
make[6]: *** [scripts/Makefile.headersinst:63: usr/include/linux/vt.h] Error 1`

This was also seen in other downstream projects before which I found when researching the error message: https://github.com/Frogging-Family/linux-tkg/issues/140#issuecomment-748462162

Removing that patch fixes the problem.

P.S: You asked me yesterday if I could test the speculative-lru patchset, I can now confirm that the speculative-lru patches apply and build fine but the order is important, I needed to apply the lru-patches before the speculative-lru patches. The other way around doesn't apply correctly.

**Comment by sirlucjan** [comment]
Yes, I know about this error. On Arch Linux everything works and that's why I keep this patch at my place. About the overlay order I know too - and it is intentional.

**Comment by ms178** [comment]
As reported yesterday in the other issue, the new version of UKSM booted fine. Feel free to close this one, if these are known errors.

**Comment by sirlucjan** [comment]
The other way was more troublesome. It is completely impossible to make it so that the order is arbitrary. Yes, the bug with the 0005-tty-Allow-setting-the-number-of-available-virtual-TT.patch is known - truthfully it only works with Arch Linux. I'm not sure about Gentoo or Slackaware - I haven't had any reports here :D
